import type { Metadata } from 'next';
import { Inter, Abel, Titillium_Web } from 'next/font/google';
import './globals.css';

// Main sans-serif (body)
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

// Heading font
const titillium = Titillium_Web({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'], // adjust to what you need
  variable: '--font-titillium',
});

// Label / UI font
const abel = Abel({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-abel',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${inter.variable}
          ${titillium.variable}
          ${abel.variable}
          antialiased
        `}
      >
        {' '}
        {children}
      </body>
    </html>
  );
}
