import type { Metadata } from 'next';
import { Inter, Abel, Titillium_Web, Pacifico } from 'next/font/google';
import './globals.css';
import SiteShell from '@/components/SiteShell';
import Footer from '@/components/Footer';
import { ContactFabMenu } from '@/components/ui/ContactFabMenu';

// Main sans-serif (body)
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

// Heading font
const titillium = Titillium_Web({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'], // adjust to what you need
  variable: '--font-titillium',
});

// Label / UI font
const abel = Abel({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-abel',
});

// Label / UI font
const pacifico = Pacifico({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-pacifico',
});

export const metadata: Metadata = {
  title: 'Yooran Kim PORTFOLIO',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`
          ${inter.variable}
          ${titillium.variable}
          ${abel.variable}
          antialiased
          relative
          w-full
          px-[1rem] md:px-[2rem] lg:px-[7rem] xl:px-[10rem]
        `}
      >
        <SiteShell>{children}</SiteShell>
        <Footer />
        <ContactFabMenu />
      </body>
    </html>
  );
}
